# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 04:01
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='fb_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
