# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20171009_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
