# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 10:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20171010_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events.FacebookPage'),
        ),
    ]
