# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-14 08:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20171113_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
